# Use root/example as user/password credentials
version: '3.1'

services:
#MySQL
  db:
    image: mysql
    container_name: mysql
    volumes:
      - db_data:var/lib/mysql
    restart: always
    networks:
      - dev_network
    environment:
      #MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: frankent
      
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: frankent
      networks:
      - dev_network

  #Network 

  networks:
  volumes: